apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  # namespace: pythonapptest
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: bish1983/bish-k8s:0.0.3
        imagePullPolicy: Always
        volumeMounts:
        - name: app-log-dir
          mountPath: /var/log/app/
        # image: nginx:latest
        ports:
        - containerPort: 80

      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.13.0
        args: ["-c", "/etc/filebeat/filebeat.yml", "-e"]
        volumeMounts:
        - name: app-log-dir
          mountPath: /var/log/app/
          readOnly: true
        - name: filebeat-config
          mountPath: /etc/filebeat/

      volumes:
      - name: app-log-dir
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: filebeat-config
