apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  # namespace: pythonapptest
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: bish1983/bish-k8s:0.0.2
        imagePullPolicy: Always
        volumeMounts:
        - name: app-log-dir
          mountPath: /var/log/app/
        # image: nginx:latest
        ports:
        - containerPort: 80
      
      volumes:
      - name: app-log-dir
        hostPath:
          path: /var/log/my-custom-app-logs
          type: DirectoryOrCreate
